# Generated by Django 5.2.5 on 2025-11-29 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_units', models.FloatField()),
                ('contract_demand', models.FloatField()),
                ('billed_demand', models.FloatField()),
                ('demand_rate', models.FloatField()),
                ('wheeling_rate', models.FloatField()),
                ('energy_rate', models.FloatField()),
                ('tod_a_units', models.FloatField()),
                ('tod_b_units', models.FloatField()),
                ('tod_c_units', models.FloatField()),
                ('tod_d_units', models.FloatField()),
                ('tod_c_rate', models.FloatField()),
                ('tod_d_rate', models.FloatField()),
                ('fac_rate', models.FloatField()),
                ('duty_percent', models.FloatField()),
                ('tax_sale_rate', models.FloatField()),
                ('incremental_rebate', models.FloatField()),
                ('prompt_discount', models.FloatField()),
                ('oa_percent', models.FloatField()),
                ('oa_energy_rate', models.FloatField()),
                ('oa_transmission_rate', models.FloatField()),
                ('oa_wheeling_rate', models.FloatField()),
                ('oa_loss_rate', models.FloatField()),
                ('oa_sldc_fixed', models.FloatField()),
                ('total_only_msedcl', models.FloatField()),
                ('total_msedcl_after', models.FloatField()),
                ('total_oa_charges', models.FloatField()),
                ('total_after_oa', models.FloatField()),
                ('savings', models.FloatField()),
                ('monthly_saving', models.FloatField()),
                ('yearly_saving', models.FloatField()),
                ('per_unit_saving', models.FloatField()),
                ('oa_units', models.FloatField()),
                ('msedcl_units_after', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
