# Generated by Django 5.2.3 on 2025-07-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='energy_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='energy_types',
            field=models.ManyToManyField(to='accounts.energytype'),
        ),
    ]
