# Generated by Django 5.2.3 on 2025-07-15 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_energytype_remove_userprofile_energy_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
