# Generated by Django 5.0 on 2026-01-08 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprovider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DSMData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('pooling_station', models.CharField(max_length=100)),
                ('energy_type', models.CharField(max_length=20)),
                ('date_time_block', models.DateTimeField()),
                ('forecasted_schedule_mal', models.FloatField()),
                ('avc', models.FloatField(blank=True, null=True)),
                ('generation', models.FloatField()),
                ('green_gen_scada', models.FloatField(blank=True, null=True)),
                ('green_gen_meter', models.FloatField(blank=True, null=True)),
                ('sems_provisional', models.FloatField(blank=True, null=True)),
                ('sem_final', models.FloatField(blank=True, null=True)),
                ('deviation_generation', models.FloatField(blank=True, null=True)),
                ('deviation_scada', models.FloatField(blank=True, null=True)),
                ('deviation_gen_meter', models.FloatField(blank=True, null=True)),
                ('deviation_sems_provisional', models.FloatField(blank=True, null=True)),
                ('deviation_sem_final', models.FloatField(blank=True, null=True)),
                ('error_in_percent', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dsm_data',
            },
        ),
        migrations.CreateModel(
            name='DSMResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_dsm', models.FloatField()),
                ('next_month_dsm', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('r2', models.FloatField(blank=True, null=True)),
                ('forecast_total', models.FloatField(blank=True, null=True)),
                ('forecast_avg', models.FloatField(blank=True, null=True)),
                ('forecast_max', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
