# Generated by Django 5.0 on 2025-10-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0002_openaccesscalculation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargemaster',
            options={'ordering': ['energy_type', 'name']},
        ),
        migrations.AddField(
            model_name='chargemaster',
            name='energy_type',
            field=models.CharField(choices=[('wind', 'Wind'), ('solar', 'Solar'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='chargemaster',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chargemaster',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='chargemaster',
            unique_together={('name', 'energy_type', 'year', 'state')},
        ),
    ]
