# Generated by Django 5.0 on 2025-10-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0003_alter_chargemaster_options_chargemaster_energy_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargemaster',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='chargemaster',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='chargemaster',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='chargemaster',
            name='energy_type',
        ),
        migrations.RemoveField(
            model_name='chargemaster',
            name='state',
        ),
    ]
