# Generated by Django 5.0 on 2025-10-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0004_alter_chargemaster_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaccesscalculation',
            name='energy_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
