# Generated by Django 5.0.6 on 2025-10-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0006_chargemaster_energy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargemaster',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
