# Generated by Django 5.0 on 2025-11-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0007_chargemaster_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakdownReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_date', models.DateField()),
                ('loc_no', models.CharField(max_length=50)),
                ('breakdown_remarks', models.TextField()),
            ],
        ),
    ]
