# Generated by Django 5.2.5 on 2025-11-26 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0008_breakdownreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChargeMaster',
        ),
        migrations.DeleteModel(
            name='OpenAccessCalculation',
        ),
    ]
